name: sync_clone_scripts_master_to_git
on:
  workflow_dispatch:
  schedule:
    - cron: '5,20,35,50 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:lan-tianxiang/clone_scripts.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:highdimen/clone_scripts.git
          
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
         token: ${{ github.token }}
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
         
